# 开发环境配置
spring:
  thymeleaf:
    cache: false
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        master:
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/local?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
        oracle:
          username: root
          password: 123456
          driver-class-name: oracle.jdbc.driver.OracleDriver
          url: jdbc:oracle:thin:@localhost:1521/company_project
        sqlServer:
          username: sa
          password: 123456
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://localhost:1433;databaseName=company_project
  redis:
    #url: # Connection URL. Overrides host, port, and password. User is ignored. Example: redis://user:password@example.com:6379
    #host: localhost # Redis server host.
    password: c7vcaziwiqgouret # Login password of the redis server.
    #port: 6379 # Redis server port.
    database: 0 # Database index used by the connection factory.
    ssl: false # Whether to enable SSL support.
    timeout: 3000 # Connection timeout milliseconds.
    #cluster:
    #  max-redirects: # Maximum number of redirects to follow when executing commands across the cluster.
    #  nodes: # Comma-separated list of "host:port" pairs to bootstrap from.
    sentinel:
      master: ESG_CR_CORE_REDIS_C01 # Name of the Redis server.
      nodes: esg-cr-core1.cache.sfdc.com.cn:8001,esg-cr-core2.cache.sfdc.com.cn:8001,esg-cr-core3.cache.sfdc.com.cn:8001 # Comma-separated list of "host:port" pairs.
    #    host: localhost # Redis服务器地址
    #    database: 0 # Redis数据库索引（默认为0）
    #    port: 6379 # Redis服务器连接端口
    #    password: # Redis服务器连接密码（默认为空）
    #    jedis:
    #      pool:
    #        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
    #        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
    #        max-idle: 8 # 连接池中的最大空闲连接
    #        min-idle: 0 # 连接池中的最小空闲连接
    #    timeout: 3000ms # 连接超时时间（毫秒:
    lettuce:
      pool:
        # 连接池最大连接数(使用负值表示没有限制) 默认为8
        max-active: 8
        # 连接池中的最大空闲连接 默认为8
        max-idle: 8
        # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
        max-wait: -1ms
        # 连接池中的最小空闲连接 默认为 0
        min-idle: 0
#    sentinel:
#      # 主节点的别名
#      master:
#      # sentinel服务的ip和端口
#      nodes:

#  mail:
#    host:
#    username:
#    password:
#    default-encoding: utf-8
file:
  #文件上传目录 绝对路径 末尾请加 /
  path: F:/files/ #windows
  #path: /data/files/ #linux
  #文件预览、下载的url, 末尾请勿加 /
  url: http://localhost:8080/files
