server:
  port: 11111

spring:

  jackson:
    time-zone: GMT+8

  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/learning-master?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
#    url: jdbc:mysql://120.79.58.4:13306/t_user_info
#    username: nc
#    password: XbnHGGo8Ku*!
    type:
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 120000
      minimum-idle: 5

  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    timeout: 10000
    lettuce:
      shutdown-timeout: 10000
      pool:
        max-active: 8
        max-wait: 0
        min-idle: 0
        max-idle: 8
#
#mybatis:
##  configuration:
##    map-underscore-to-camel-case: true
#  type-aliases-package: com.fff.springbootapiseedtest.model
#  mapper-locations: classpath*:mapper/*.xml

logging:
  config: classpath:mylogback-spring.xml
  level:
    root: info