server:
  port: 11112
  servlet:
    context-path: /
#  gzip 开启
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
#  tomcat中使用gzip需要进行配置，在server.xml中，在Connector标签中加入如下属性
#  compression="on"
#  compressionMinSize="2048"
#  compressableMimeType="text/html,text/css,text/javascript"

spring:

  application:
    name: springboot-tool
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
#    图标 不适用
    favicon:
      enabled: false
  resources:
    add-mappings: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  aop:
    auto: true #启动aop配置
  # 文件大小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#  datasource:
#    platform: mysql
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/learning-master?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
#    url: jdbc:mysql://120.79.58.4:13306/t_user_info
#    username: nc
#    password: XbnHGGo8Ku*!
#    type:
#    hikari:
#      maximum-pool-size: 5
#      connection-timeout: 30000
#      idle-timeout: 60000
#      max-lifetime: 120000
#      minimum-idle: 5
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    timeout: 10000
    lettuce:
      shutdown-timeout: 10000
      pool:
        max-active: 8
        max-wait: 0
        min-idle: 0
        max-idle: 8
    prefix:
      enable: true
      key: E00P01
  thymeleaf:
    prefix: classpath:/templates/   # 访问template下的html文件需要配置模板，映射
    suffix: .html
    cache: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1

logging:
  config: classpath:mylogback-spring.xml
  level:
    root: info
    com.xuegao.springboot_tool.dao: debug

felord:
  phone: 182******32
  def:
    name: 码农小胖哥
    blog: felord.cn
    we-chat: MSW_623
  dev:
    name: 码农小胖哥
    blog: felord.cn
    we-chat: MSW_623
  type: JUEJI
demo:
  username: lengleng
  password: 123456
#使用代码生成模块时 指定要生成的表存在于哪种数据库，可选值有【mysql、oracle、sqlServer】
project:
  database: mysql