server:
  port: 11112
  servlet:
    context-path: /
  #  gzip 开启
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
#  tomcat中使用gzip需要进行配置，在server.xml中，在Connector标签中加入如下属性
#  compression="on"
#  compressionMinSize="2048"
#  compressableMimeType="text/html,text/css,text/javascript"

spring:
  application:
    name: springboot-tool
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
    #    图标 不适用
    favicon:
      enabled: false
  resources:
    add-mappings: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  aop:
    auto: true #启动aop配置
  # 文件大小限制
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 2MB  #设置支持的单个上传文件大小
#      max-request-size: 6MB  #设置最大的请求文件大小，设置总体大小的请求
#      file-size-threshold: 512KB #当上传文件达到指定配置量的时候，会将文件内容写入到磁盘
#      location: /   #设置上传文件的临时目录

  #  datasource:
  #    platform: mysql
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://127.0.0.1:3306/learning-master?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  #    username: root
  #    password: 123456
  #    url: jdbc:mysql://120.79.58.4:13306/t_user_info
  #    username: nc
  #    password: XbnHGGo8Ku*!
  #    type:
  #    hikari:
  #      maximum-pool-size: 5
  #      connection-timeout: 30000
  #      idle-timeout: 60000
  #      max-lifetime: 120000
  #      minimum-idle: 5
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    timeout: 10000
    lettuce:
      shutdown-timeout: 10000
      pool:
        max-active: 8
        max-wait: 0
        min-idle: 0
        max-idle: 8
    prefix:
      enable: true
      key: E00P01
  thymeleaf:
    prefix: classpath:/templates/   # 访问template下的html文件需要配置模板，映射
    suffix: .html
    cache: false
#  data:
#    mongodb:
#      database: bfa_mongo
#      username: "xxx"
#      password: "xxxxx"
#      address: "host:port"
#      address: 集群
#        - "host:port"
#        - "host2:port2"
#        -
#      authenticationDatabase: [设置你的认证数据库，如果有的话]
#      # 连接池配置
#      clientName: ${spring.application.name} # 客户端的标识，用于定位请求来源等
#      connectionTimeoutMs: 10000     # TCP连接超时，毫秒
#      readTimeoutMs: 15000       # TCP读取超时，毫秒
#      poolMaxWaitTimeMs: 3000        #当连接池无可用连接时客户端阻塞等待的时长，单位毫秒
#      connectionMaxIdleTimeMs: 60000   #TCP连接闲置时间，单位毫秒
#      connectionMaxLifeTimeMs: 120000    #TCP连接最多可以使用多久，单位毫秒
#      heartbeatFrequencyMs: 20000      #心跳检测发送频率，单位毫秒
#      minHeartbeatFrequencyMs: 8000    #最小的心跳检测发送频率，单位毫秒
#      heartbeatConnectionTimeoutMs: 10000  #心跳检测TCP连接超时，单位毫秒
#      heartbeatReadTimeoutMs: 15000    #心跳检测TCP连接读取超时，单位毫秒
#      connectionsPerHost: 20       # 每个host的TCP连接数
#      minConnectionsPerHost: 5     #每个host的最小TCP连接数
#      #计算允许多少个线程阻塞等待可用TCP连接时的乘数，算法：threadsAllowedToBlockForConnectionMultiplier*connectionsPerHost，当前配置允许10*20个线程阻塞
#      threadsAllowedToBlockForConnectionMultiplier: 10

mybatis-plus:
#  config-location: classpath:mybatis-config.xml # 配置 MyBatis 配置文件路径
  mapper-locations: classpath:mapper/*.xml  # 配置 Mapper XML 地址
  typeAliasesPackage: com.xuegao.springboot_tool.dao  # 配置数据库实体包路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: true
  global-config:
    db-config:
      #数据库大写下划线转换
      capital-mode: false
      #删除
      logic-delete-value: 1
      #不删除
      logic-not-delete-value: 0

logging:
  #  由于引入了 log4j2，不再是 logback，，先注释
  #  config: classpath:mylogback-spring.xml
  config: classpath:log4j2-spring.xml
  level:
    root: info
    cn.jay.repository: trace
    com.xuegao.springboot_tool.dao: debug

felord:
  phone: 182******32
  def:
    name: 码农小胖哥
    blog: felord.cn
    we-chat: MSW_623
  dev:
    name: 码农小胖哥
    blog: felord.cn
    we-chat: MSW_623
  type: JUEJI
demo:
  username: lengleng
  password: 123456
#使用代码生成模块时 指定要生成的表存在于哪种数据库，可选值有【mysql、oracle、sqlServer】
project:
  database: mysql


